package com.services.login.modelo;
// Generated 06-feb-2017 20:11:58 by Hibernate Tools 5.0.0.Alpha3

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.springframework.format.annotation.DateTimeFormat;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", schema = "public")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 191948985863207488L;
	private String username;
	private String contrasena;
	private String nombres;
	private Integer cedula;
	private String unidad;
	private String email;
	private String grupo;
	private String nivel;
	private String telefonos;
	private Character estatus;
	private String cempresa;
	private Character caduca;
	private Date fechaUltimoCambio;

	public Usuarios() {
	}

	public Usuarios(String username, String contrasena, String nombres) {
		this.username = username;
		this.contrasena = contrasena;
		this.nombres = nombres;
	}

	public Usuarios(String username, String contrasena, String nombres, Integer cedula, String unidad, String email,
			String grupo, String nivel, String telefonos, Character estatus, String cempresa, Character caduca,
			Date fechaUltimoCambio) {
		this.username = username;
		this.contrasena = contrasena;
		this.nombres = nombres;
		this.cedula = cedula;
		this.unidad = unidad;
		this.email = email;
		this.grupo = grupo;
		this.nivel = nivel;
		this.telefonos = telefonos;
		this.estatus = estatus;
		this.cempresa = cempresa;
		this.caduca = caduca;
		this.fechaUltimoCambio = fechaUltimoCambio;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 15)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "contrasena", nullable = false, length = 64)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "nombres", nullable = false, length = 100)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "cedula")
	public Integer getCedula() {
		return this.cedula;
	}

	public void setCedula(Integer cedula) {
		this.cedula = cedula;
	}

	@Column(name = "unidad", length = 10)
	public String getUnidad() {
		return this.unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "grupo", length = 200)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "nivel", length = 2)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	@Column(name = "telefonos", length = 100)
	public String getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(String telefonos) {
		this.telefonos = telefonos;
	}

	@Column(name = "estatus", length = 1)
	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

	@Column(name = "cempresa", length = 5)
	public String getCempresa() {
		return this.cempresa;
	}

	public void setCempresa(String cempresa) {
		this.cempresa = cempresa;
	}
	
	@Column(name = "caduca", length = 1)
	public Character getCaduca() {
		return this.caduca;
	}

	public void setCaduca(Character caduca) {
		this.caduca = caduca;
	}

	@Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern="yyyy-MM-dd") 
	@Column(name = "fecha_ultimo_cambio", length = 13)
	public Date getFechaUltimoCambio() {
		return this.fechaUltimoCambio;
	}

	public void setFechaUltimoCambio(Date fechaUltimoCambio) {
		this.fechaUltimoCambio = fechaUltimoCambio;
	}

}
